import test from 'node:test';import assert from 'node:assert/strict';
import {InventoryService,emptyState,ConsumptionPolicy} from '../web/domain.js';
let serial=0;const cmd=(type,payload)=>({id:`op-${++serial}`,type,payload,actor:'test',at:'2026-09-26T00:00:00Z'});
function setup(volume=720){let s=InventoryService.apply(emptyState(),cmd('addFridge',{id:'f',name:'冷蔵庫'}));s=InventoryService.apply(s,cmd('addFridge',{id:'f2',name:'冷蔵庫2'}));return InventoryService.apply(s,cmd('receive',{name:'試験酒',volume,count:1,ids:['b'],fridgeId:'f'}));}
test('720ml: four servings, no negative remainder',()=>{let s=setup();for(let v=1;v<=4;v++)s=InventoryService.apply(s,cmd('consume',{bottleId:'b',version:v}));assert.equal(s.bottles[0].remaining,0);assert.throws(()=>InventoryService.apply(s,cmd('consume',{bottleId:'b',version:5})));});
test('300ml consumes one whole bottle',()=>{let s=setup(300);s=InventoryService.apply(s,cmd('consume',{bottleId:'b',version:1}));assert.equal(s.bottles[0].remaining,0);assert.equal(ConsumptionPolicy.label(300),'1本');});
test('1800ml is ten servings and retry is idempotent',()=>{const s=setup(1800),c=cmd('consume',{bottleId:'b',version:1});const once=InventoryService.apply(s,c);assert.equal(once.bottles[0].remaining,1620);assert.deepEqual(InventoryService.apply(once,c),once);});
test('stale update and repeated undo rejected',()=>{let s=setup(),c=cmd('consume',{bottleId:'b',version:1});s=InventoryService.apply(s,c);assert.throws(()=>InventoryService.apply(s,cmd('move',{bottleId:'b',version:1,fridgeId:'f2'})));s=InventoryService.apply(s,cmd('undo',{bottleId:'b',version:2,eventId:c.id}));assert.equal(s.bottles[0].remaining,720);assert.equal(s.bottles[0].openedAt,null);assert.throws(()=>InventoryService.apply(s,cmd('undo',{bottleId:'b',version:3,eventId:c.id})));});
test('move keeps volume and bottle identity',()=>{let s=setup();s=InventoryService.apply(s,cmd('move',{bottleId:'b',version:1,fridgeId:'f2',shelf:'上段'}));assert.equal(s.bottles[0].remaining,720);assert.equal(s.bottles[0].fridgeId,'f2');assert.equal(s.bottles[0].id,'b');});
test('remainder finish and backup replay',()=>{let s=setup(500);s=InventoryService.apply(s,cmd('consume',{bottleId:'b',version:1}));s=InventoryService.apply(s,cmd('consume',{bottleId:'b',version:2}));assert.equal(s.bottles[0].remaining,140);s=InventoryService.apply(s,cmd('finish',{bottleId:'b',version:3}));const replay=s.events.reduce((state,e)=>InventoryService.apply(state,e.command),emptyState());assert.deepEqual(replay.bottles,s.bottles);});
test('unknown fridge, duplicate bottles and fractions rejected',()=>{let s=setup();for(const p of [{volume:720,count:1,ids:['b'],fridgeId:'f'},{volume:720,count:1,ids:['new'],fridgeId:'absent'},{volume:720,count:1.5,ids:['new'],fridgeId:'f'}])assert.throws(()=>InventoryService.apply(s,cmd('receive',{name:'試験',...p})));});
