import test from 'node:test';import assert from 'node:assert/strict';
import {InventoryService,emptyState} from '../web/domain.js';import {validateSnapshot} from '../web/migration.js';
const c=(id,type,payload)=>({id,type,payload,at:'2026-09-26T00:00:00Z',actor:'test'});
function snapshot(){let s=InventoryService.apply(emptyState(),c('f','addFridge',{id:'f',name:'冷蔵庫'}));s=InventoryService.apply(s,c('b','receive',{ids:['b'],name:'酒',volume:720,count:1,fridgeId:'f'}));s=InventoryService.apply(s,c('drink','consume',{bottleId:'b',version:1}));return validateSnapshot(s);}
test('migration preserves partial bottle and leaves input untouched',()=>{const source=snapshot(),before=structuredClone(source);const s=InventoryService.apply(emptyState(),c('import','importPersonal',{snapshot:source}));assert.equal(s.bottles[0].remaining,540);assert.equal(s.bottles[0].version,1);assert.equal(s.bottles[0].openedAt,source.bottles[0].openedAt);assert.deepEqual(source,before);});
test('reimport after shared consumption neither duplicates nor overwrites',()=>{const source=snapshot();let s=InventoryService.apply(emptyState(),c('import','importPersonal',{snapshot:source}));s=InventoryService.apply(s,c('drink','consume',{bottleId:'b',version:1}));s=InventoryService.apply(s,c('import-again','importPersonal',{snapshot:source}));assert.equal(s.bottles.length,1);assert.equal(s.bottles[0].remaining,360);assert.equal(s.events.at(-1).skipped,1);});
test('invalid snapshot cannot partly add refrigerators',()=>{const source=snapshot();source.bottles[0].remaining=-1;const original=emptyState();assert.throws(()=>InventoryService.apply(original,c('i','importPersonal',{snapshot:source})));assert.equal(original.refrigerators.length,0);});
test('reject fractional 300ml bottle and duplicate IDs',()=>{const source=snapshot();source.bottles[0].volume=300;source.bottles[0].remaining=120;assert.throws(()=>validateSnapshot(source));const duplicate=snapshot();duplicate.bottles.push(duplicate.bottles[0]);assert.throws(()=>validateSnapshot(duplicate));});
test('regular bottle ID collision is rejected',()=>{const source=snapshot();const target={...source,events:[]};assert.throws(()=>InventoryService.apply(target,c('i','importPersonal',{snapshot:source})));});
