import test from 'node:test';import assert from 'node:assert/strict';
import {ServerRepository} from '../web/repositories.js';import {InventoryService,emptyState} from '../web/domain.js';
class MemoryStore {constructor(){this.value=emptyState();}async read(){return structuredClone(this.value);}async change(fn){this.value=fn(structuredClone(this.value));return this.read();}}
function setup(){let remote=emptyState();const api={async request(path,opts){if(path==='/api/state')return structuredClone(remote);remote=InventoryService.apply(remote,JSON.parse(opts.body));return structuredClone(remote);}};const r=new ServerRepository(api,'test');r.cache=new MemoryStore();return {r,api,get remote(){return remote;}};}
const c=(id,type,payload)=>({id,type,payload,actor:'test',at:'2026-09-26T00:00:00Z'});
const online=value=>Object.defineProperty(navigator,'onLine',{configurable:true,value});
test('offline queue persists and flushes once in order',async()=>{online(false);const {r,remote,...rest}=setup();await r.execute(c('1','addFridge',{id:'f',name:'自宅'}));await r.execute(c('2','receive',{name:'酒',volume:300,count:1,ids:['b'],fridgeId:'f'}));await r.execute(c('3','consume',{bottleId:'b',version:1}));assert.equal(await r.pendingCount(),3);assert.equal((await r.read()).bottles[0].remaining,0);online(true);await r.flush();await r.flush();assert.equal(await r.pendingCount(),0);assert.equal((await r.read()).events.length,3);});
test('lost response retries same ID without duplicate consumption',async()=>{online(true);const env=setup(),r=env.r;await r.execute(c('1','addFridge',{id:'f',name:'自宅'}));await r.execute(c('2','receive',{name:'酒',volume:720,count:1,ids:['b'],fridgeId:'f'}));const original=env.api.request.bind(env.api);let drop=true;env.api.request=async(...args)=>{const response=await original(...args);if(drop&&args[0]==='/api/commands'){drop=false;throw new Error('通信断');}return response;};await r.execute(c('3','consume',{bottleId:'b',version:1}));assert.equal(await r.pendingCount(),1);await r.flush();assert.equal((await r.read()).bottles[0].remaining,540);assert.equal(env.remote.events.length,3);});
test('conflict retained until explicit discard, no remote overwrite',async()=>{online(true);const env=setup(),r=env.r;await r.execute(c('1','addFridge',{id:'f',name:'自宅'}));await r.execute(c('2','receive',{name:'酒',volume:720,count:1,ids:['b'],fridgeId:'f'}));online(false);await r.execute(c('3','consume',{bottleId:'b',version:1}));await env.api.request('/api/commands',{body:JSON.stringify(c('other','consume',{bottleId:'b',version:1}))});online(true);await r.read();assert.match(r.syncError,/更新/);assert.equal(await r.pendingCount(),1);assert.equal(env.remote.bottles[0].remaining,540);await r.discardPending();assert.equal(await r.pendingCount(),0);});
