import {InventoryService,ConsumptionPolicy,remainingLabel,emptyState,id} from './domain.js';
import {LocalRepository,ServerRepository,ApiClient,RecognitionService} from './repositories.js';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=emptyState(), repo=new LocalRepository(), mode='personal', actor='個人', photo='', busy=false, moving=null;
let api=new ApiClient(sessionStorage.getItem('bacchus-token')||'');
let toastTimer;
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,7000);}
function options(selected='',all=false){return `${all?'<option value="">すべての冷蔵庫</option>':''}${state.refrigerators.map(f=>`<option value="${esc(f.id)}" ${f.id===selected?'selected':''}>${esc(f.name)}</option>`).join('')}`;}
function location(b){return `${state.refrigerators.find(f=>f.id===b.fridgeId)?.name||'未設定'}${b.shelf?' / '+b.shelf:''}`;}
function date(value){return new Date(value).toLocaleString('ja-JP',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});}
async function render(){
  $('#bottleCount').textContent=state.bottles.filter(b=>b.remaining>0).length;
  const pending=repo instanceof ServerRepository?await repo.pendingCount():0;
  $('#modeLabel').textContent=mode==='shared'?`共用・サーバー保存${pending?`（${pending}件保留）`:''}`:'個人用・端末保存';
  $('#syncStatus').textContent=mode==='shared'?`${pending}件の保留操作。${repo.syncError||'同期済みの在庫と端末の保留分を表示します。'}`:'個人用は端末に保存しています。';
  const selected=$('#fridgeFilter').value;$('#fridgeFilter').innerHTML=options(selected,true);
  const query=$('#search').value.toLowerCase(),fridge=$('#fridgeFilter').value;
  const bottles=state.bottles.filter(b=>(b.remaining>0||$('#showEmpty').checked)&&(!fridge||b.fridgeId===fridge)&&`${b.name} ${b.brewery}`.toLowerCase().includes(query));
  $('#bottles').innerHTML=bottles.map(b=>`<article class="card"><div class="bottleTop">${b.photo?`<img src="${esc(b.photo)}" alt="${esc(b.name)}のラベル">`:'<div class="placeholder" aria-hidden="true">🍶</div>'}<div><span class="badge">${b.volume} ml · ${b.openedAt?'開封済み':'未開封'}</span><h3>${esc(b.name)}</h3><div class="meta">${esc(b.brewery||'酒蔵未登録')}<br>${esc(location(b))}</div></div></div><p class="remaining">${remainingLabel(b)} <small>残量 ${b.remaining} ml</small></p><progress value="${b.remaining}" max="${b.volume}" aria-label="残量"></progress><div class="actions"><button data-consume="${esc(b.id)}" ${b.remaining===0?'disabled':''}>${b.remaining>0&&b.remaining<ConsumptionPolicy.unit(b.volume)?'残りを飲み切る':ConsumptionPolicy.label(b.volume)+'消費'}</button><button data-move="${esc(b.id)}" class="quiet">移動</button></div></article>`).join('')||'<div class="empty"><strong>日本酒を迎えましょう</strong>冷蔵庫を追加して、最初の一本を登録。<br>検索中の場合は条件を変更してください。</div>';
  $('#fridgeList').innerHTML=state.refrigerators.map(f=>{const bs=state.bottles.filter(b=>b.fridgeId===f.id&&b.remaining>0);return `<article class="card"><span class="badge">冷蔵庫</span><h3>${esc(f.name)}</h3><p>${bs.length}本 <span class="muted">／ ${bs.reduce((n,b)=>n+b.remaining,0).toLocaleString()} ml</span></p><button class="secondary full" data-filter="${esc(f.id)}">この冷蔵庫を見る</button></article>`;}).join('')||'<div class="empty">「＋ 冷蔵庫」から保管場所を追加してください。</div>';
  const names={receive:'入荷',consume:'消費',finish:'飲み切り',move:'移動',undo:'取り消し',addFridge:'冷蔵庫追加'};
  $('#eventList').innerHTML=state.events.slice().reverse().slice(0,200).map(e=>{const b=state.bottles.find(b=>b.id===e.bottleId);const undo=['consume','finish','move'].includes(e.type)&&b?.version===e.after?.version&&!state.events.some(x=>x.undoOf===e.id);return `<div class="event"><div><small>${esc(date(e.at))} · ${esc(e.actor)}</small><p><b>${names[e.type]||esc(e.type)}</b> ${esc(e.name)} ${e.amount?`· ${e.amount}ml`:''}</p>${e.type==='move'?`<small>${esc(location(e.before))} → ${esc(location(e.after))}</small>`:''}</div>${undo?`<button class="quiet" data-undo="${esc(e.id)}">取消</button>`:''}</div>`;}).join('')||'<div class="empty">履歴はまだありません。</div>';
}
async function guard(fn){if(busy)return;busy=true;document.body.setAttribute('aria-busy','true');try{await fn();}catch(e){toast(e.message||'操作できませんでした');}finally{busy=false;document.body.removeAttribute('aria-busy');}}
async function execute(type,payload){const command={id:id(),type,payload,actor,at:new Date().toISOString()};state=await repo.execute(command);await render();toast(repo.syncError?`端末に保留しました。${repo.syncError}`:mode==='shared'&&!navigator.onLine?'通信復旧後に同期します':'記録しました');}
function tab(name){for(const n of ['inventory','fridges','history'])$('#'+n).hidden=n!==name;document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('selected',b.dataset.tab===name));}
function openRegister(){if(!state.refrigerators.length){toast('先に冷蔵庫を追加してください');$('#fridgeDialog').showModal();return;}$('#registerForm').reset();photo='';$('#photoInput').value='';$('#photoPreview').hidden=true;$('#recognize').disabled=true;$('#aiStatus').textContent='';$('#unitHint').textContent='消費は1合（180ml）単位';$('#registerForm [name=fridgeId]').innerHTML=options(localStorage.getItem('lastFridge')||state.refrigerators[0].id);$('#registerForm [name=shelf]').value=localStorage.getItem('lastShelf')||'';$('#registerDialog').showModal();}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.close)$('#'+b.dataset.close).close();if(b.dataset.tab)tab(b.dataset.tab);if(b.dataset.filter){$('#fridgeFilter').value=b.dataset.filter;tab('inventory');render();}
if(b.dataset.consume)guard(async()=>{const bottle=state.bottles.find(x=>x.id===b.dataset.consume);const type=bottle.remaining<ConsumptionPolicy.unit(bottle.volume)?'finish':'consume';await execute(type,{bottleId:bottle.id,version:bottle.version});});
if(b.dataset.move){moving=state.bottles.find(x=>x.id===b.dataset.move);const form=$('#moveForm');form.elements.bottleId.value=moving.id;form.elements.version.value=moving.version;form.elements.fridgeId.innerHTML=options(moving.fridgeId);form.elements.shelf.value=moving.shelf;$('#moveDialog').showModal();}
if(b.dataset.undo)guard(async()=>{const event=state.events.find(x=>x.id===b.dataset.undo),bottle=state.bottles.find(x=>x.id===event.bottleId);await execute('undo',{bottleId:bottle.id,version:bottle.version,eventId:event.id});});});
$('#registerButton').onclick=openRegister;$('#addFridge').onclick=()=>$('#fridgeDialog').showModal();
for(const el of ['search','fridgeFilter','showEmpty'])$('#'+el).addEventListener('input',()=>render());
$('#refresh').onclick=()=>guard(async()=>{state=await repo.read();await render();if(repo.syncError)toast(repo.syncError);});
$('#fridgeForm').onsubmit=e=>{e.preventDefault();guard(async()=>{await execute('addFridge',{id:id(),name:e.target.elements.name.value});e.target.reset();$('#fridgeDialog').close();});};
$('#registerForm').onsubmit=e=>{e.preventDefault();guard(async()=>{const p=Object.fromEntries(new FormData(e.target));p.volume=Number(p.volume);p.count=Number(p.count);p.ids=Array.from({length:p.count},id);p.photo=photo;await execute('receive',p);localStorage.setItem('lastFridge',p.fridgeId);localStorage.setItem('lastShelf',p.shelf);$('#registerDialog').close();tab('inventory');});};
$('#moveForm').onsubmit=e=>{e.preventDefault();guard(async()=>{const p=Object.fromEntries(new FormData(e.target));p.version=Number(p.version);await execute('move',p);$('#moveDialog').close();});};
$('#registerForm [name=volume]').oninput=e=>$('#unitHint').textContent=Number(e.target.value)===300?'消費は1本（300ml）単位':'消費は1合（180ml）単位。端数は「残りを飲み切る」で記録できます。';
async function resizePhoto(file){
  if(!file||file.size>20000000)throw new Error('20MB以下の画像を選択してください');
  const url=URL.createObjectURL(file);try{const img=new Image();img.src=url;await img.decode();const scale=Math.min(1,1280/Math.max(img.width,img.height));const canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);const data=canvas.toDataURL('image/jpeg',.8);if(data.length>1600000)throw new Error('写真が大きすぎます。近づいて撮り直してください');return data;}finally{URL.revokeObjectURL(url);}}
$('#photoInput').onchange=e=>guard(async()=>{if(!e.target.files[0])return;photo=await resizePhoto(e.target.files[0]);$('#photoPreview').src=photo;$('#photoPreview').hidden=false;$('#recognize').disabled=false;$('#aiStatus').textContent='写真を確認してAI解析、または手入力してください。';});
$('#recognize').onclick=()=>guard(async()=>{if(!api.token)throw new Error('設定で接続トークンを入力するとAIを使えます。写真を保存して手入力登録もできます。');$('#recognize').disabled=true;$('#aiStatus').textContent='ラベルを読み取っています…';try{const result=await new RecognitionService(api).recognize(photo);for(const key of ['name','brewery','category','productionDate','volume']){if(result[key]!==null&&result[key]!==undefined&&result[key]!=='')$('#registerForm').elements[key].value=result[key];}$('#registerForm [name=volume]').dispatchEvent(new Event('input'));$('#aiStatus').textContent='読み取り完了。銘柄・容量・製造年月を確認してください。'+(result.notes||'');}catch(e){$('#aiStatus').textContent=e.message;throw e;}finally{$('#recognize').disabled=false;}});
$('#settingsButton').onclick=()=>{$('#storageMode').value=mode;$('#token').value=api.token;$('#settingsDialog').showModal();};
$('#settingsForm').onsubmit=e=>{e.preventDefault();guard(async()=>{const newApi=new ApiClient($('#token').value.trim()),newMode=$('#storageMode').value;let newRepo=new LocalRepository(),newActor='個人';if(newMode==='shared'||newApi.token){const session=await newApi.request('/api/session');newActor=session.user;localStorage.setItem('bacchus-workspace',session.workspace);if(newMode==='shared')newRepo=new ServerRepository(newApi,session.workspace);}const newState=await newRepo.read();api=newApi;repo=newRepo;state=newState;actor=newActor;mode=newMode;sessionStorage.setItem('bacchus-token',api.token);sessionStorage.setItem('bacchus-actor',actor);localStorage.setItem('bacchus-mode',mode);await render();$('#settingsDialog').close();toast('保存先を変更しました');});};
function download(data,name){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('#export').onclick=()=>guard(async()=>{const envelope={application:'BACCHUS-SYSTEM',schema:1,mode,exportedAt:new Date().toISOString(),state};if(repo instanceof ServerRepository)envelope.shared=await repo.cache.read();download(envelope,`bacchus-backup-${new Date().toISOString().slice(0,10)}.json`);toast('バックアップを保存しました');});
function validateBackup(data){if(data.application!=='BACCHUS-SYSTEM'||data.schema!==1||data.mode!=='personal'||!Array.isArray(data.state?.events))throw new Error('個人用のBACCHUSバックアップを選択してください');let reconstructed=emptyState();for(const event of data.state.events){if(!event.command)throw new Error('このバックアップは復元形式に対応していません');reconstructed=InventoryService.apply(reconstructed,event.command);}return reconstructed;}
$('#import').onchange=e=>guard(async()=>{const f=e.target.files[0];try{if(!f)return;if(mode!=='personal')throw new Error('個人用モードに切り替えてください');if(f.size>50000000)throw new Error('バックアップが大きすぎます');const restored=validateBackup(JSON.parse(await f.text()));if(!confirm('現在の個人用在庫をバックアップの内容に置き換えます。よろしいですか？'))return;state=await repo.change(()=>restored);await render();toast('個人データを復元しました');}finally{e.target.value='';}});
$('#sync').onclick=()=>guard(async()=>{if(!(repo instanceof ServerRepository))throw new Error('共用モードで使用できます');await repo.flush();state=await repo.read();await render();if(repo.syncError)throw new Error(repo.syncError);toast('同期しました');});
$('#discardPending').onclick=()=>guard(async()=>{if(!(repo instanceof ServerRepository))throw new Error('共用モードで使用できます');if(!confirm('保留中の操作をすべて破棄して、サーバーの状態を取得します。必要なら先にバックアップしてください。'))return;state=await repo.discardPending();await render();toast('サーバーの状態を取得しました');});
async function connectionChanged(){$('#offline').hidden=navigator.onLine;if(navigator.onLine&&repo instanceof ServerRepository&&!busy)await guard(async()=>{state=await repo.read();await render();if(repo.syncError)toast(repo.syncError);});}
window.addEventListener('online',connectionChanged);window.addEventListener('offline',connectionChanged);
async function init(){try{if(localStorage.getItem('bacchus-mode')==='shared'){const workspace=localStorage.getItem('bacchus-workspace');if(workspace){mode='shared';actor=sessionStorage.getItem('bacchus-actor')||'共用利用者';repo=new ServerRepository(api,workspace);}}state=await repo.read();await render();if(repo.syncError)toast(repo.syncError);}catch(e){toast(e.message);}$('#offline').hidden=navigator.onLine;if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>toast('オフライン起動にはHTTPS接続が必要です'));}
init();
